name: ci
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Get cache paths
        id: cache
        run: |
          echo "build=$(go env GOCACHE)" | tee -a $GITHUB_OUTPUT
          echo "module=$(go env GOMODCACHE)" | tee -a $GITHUB_OUTPUT

      - name: Set up cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ${{ steps.cache.outputs.build }}
            ${{ steps.cache.outputs.module }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

      - name: Run tests
        run: TF_ACC_TERRAFORM_PATH="$(command -v terraform)" go test -race ./...

  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Get cache paths
        id: cache
        run: |
          echo "build=$(go env GOCACHE)" | tee -a $GITHUB_OUTPUT
          echo "module=$(go env GOMODCACHE)" | tee -a $GITHUB_OUTPUT

      - name: Set up cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ${{ steps.cache.outputs.build }}
            ${{ steps.cache.outputs.module }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

      - name: Generate documentation
        run: TF_ACC_TERRAFORM_PATH="$(command -v terraform)" go generate ./...

      - name: Check for uncommitted changes
        run: |
          git add .
          git diff --staged --exit-code

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Get cache paths
        id: cache
        run: |
          echo "build=$(go env GOCACHE)" | tee -a $GITHUB_OUTPUT
          echo "module=$(go env GOMODCACHE)" | tee -a $GITHUB_OUTPUT

      - name: Set up cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ${{ steps.cache.outputs.build }}
            ${{ steps.cache.outputs.module }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports

      - name: Format code, clean up imports and module dependencies
        run: |
          go fmt ./...
          goimports -w -local github.com/tailscale .
          go mod tidy

      - name: Check for uncommitted changes
        run: |
          git add .
          git diff --staged --exit-code

  licenses:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: check licenses
        run: ./scripts/check_license_headers.sh .
